FROM quay.io/redhat-appstudio-qe/build-e2e-iueh-tenant/build-suite-component-update-zyib/multi-component-parent-vqlc@sha256:d0ea609546c304bc57dd4453b80e5b0d2be8cf795968d14c94f3439e97765334
RUN echo hello
