FROM quay.io/redhat-appstudio-qe/build-e2e-xqkt-tenant/build-suite-component-update-dfnu/multi-component-parent-ybwf@sha256:1f0904353de6acaa951082ea6cda4cb20c99ee8d5661c71562df9322c6364d95
RUN echo hello
